import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Store } from '../shared/browser-bot/store.mjs';
import { BrowserJobBroker } from '../belmont-browse/src/browser-job-broker.mjs';
import { ReadOnlyRfbFilter } from '../belmont-browse/src/browser-screen.mjs';
function fixture(){const dir=mkdtempSync(join(tmpdir(),'browser-bot-'));let now=1000000;const calls=[];const handles=new Map();const engine={
 get:key=>handles.get(key),asideMessages:async()=>[],stats:()=>({running:0}),
 startSession:options=>{calls.push(options);const h={id:options.sessionId??`native-${calls.length}`,status:'running',suspension:null,toJSON(){return{id:this.id,status:this.status,suspension:this.suspension,result:this.status==='done'?'complete':null,error:null};},async answer(){this.status='running';},async steer(t){calls.push({steer:t,id:this.id});},continue(t){this.status='running';calls.push({continue:t,id:this.id});},async stop(){this.status='stopped';}};handles.set(h.id,h);return h;}
};const file=join(dir,'jobs.sqlite');const broker=new BrowserJobBroker({file,engine,botId:'browser-bot-1234',instanceId:'instance-1',now:()=>now,log:()=>{}});return{dir,file,broker,engine,calls,handles,setNow:v=>now=v,close:async()=>{await broker.close();rmSync(dir,{recursive:true,force:true});}};}
const request=(jobId,requestKey=jobId)=>({botId:'browser-bot-1234',requesterAgentId:'worker-a',replyTarget:'worker-a',jobId,requestId:requestKey,requestKey,task:`do ${jobId}`,expectedInstanceId:'instance-1'});
test('a repeated request is one durable intake, conflict fails',async()=>{const f=fixture();try{const a=f.broker.submit(request('a'));const b=f.broker.submit(request('a'));assert.equal(a.key,b.key);assert.throws(()=>f.broker.submit({...request('a'),task:'different'}),/different input/);await f.broker.tick();await f.broker.tick();assert.equal(f.calls.length,1);}finally{await f.close();}});
test('two independent jobs use different native sessions and serialize',async()=>{const f=fixture();try{const a=f.broker.submit(request('a')),b=f.broker.submit(request('b'));await f.broker.tick();assert.equal(f.calls.length,1);const j=f.broker.get(a.jobKey);f.handles.get(j.asideSessionId).status='done';await f.broker.tick();assert.equal(f.calls.length,2);assert.notEqual(f.broker.get(a.jobKey).asideSessionId,f.broker.get(b.jobKey).asideSessionId);}finally{await f.close();}});
test('waiting approval holds browser and does not count as running time',async()=>{const f=fixture();try{const a=f.broker.submit(request('a'));f.broker.submit(request('b'));await f.broker.tick();const h=f.handles.get(f.broker.get(a.jobKey).asideSessionId);h.status='suspended';h.suspension={kind:'approval',toolCallId:'q-1',description:'Confirm'};await f.broker.tick();const before=f.broker.get(a.jobKey).runningMs;f.setNow(2000000);await f.broker.tick();assert.equal(f.calls.length,1);assert.equal(f.broker.get(a.jobKey).runningMs,before);assert.throws(()=>f.broker.answer(a.jobKey,{actor:'worker-a',requestKey:'answer',expectedInstanceId:'instance-1',expectedSessionId:h.id,expectedToolCallId:'q-1',response:{}}),/Delegating bots/);}finally{await f.close();}});
test('missing native session is unknown and is not replayed',async()=>{const f=fixture();try{const a=f.broker.submit(request('a'));await f.broker.tick();f.handles.clear();await f.broker.tick();await f.broker.tick();assert.equal(f.calls.length,1);assert.equal(f.broker.get(a.jobKey).status,'unknown');}finally{await f.close();}});
test('restart retains receipts and blocks ambiguous replay',async()=>{const f=fixture();try{const a=f.broker.submit(request('a'));await f.broker.tick();await f.broker.close();const second=new BrowserJobBroker({file:f.file,engine:f.engine,botId:'browser-bot-1234',instanceId:'instance-2',log:()=>{}});assert.equal(second.get(a.jobKey).status,'unknown');await second.tick();assert.equal(f.calls.length,1);assert.equal(second.receipt('worker-a','a').jobKey,a.jobKey);await second.close();}finally{rmSync(f.dir,{recursive:true,force:true});}});
test('display projection deduplicates atomically across reload',()=>{const dir=mkdtempSync(join(tmpdir(),'mirror-')),file=join(dir,'db');try{let s=new Store(file);s.event('instance/session/message','bot',{origin:'aside-mirror',text:'once'});s.close();s=new Store(file);s.event('instance/session/message','bot',{origin:'aside-mirror',text:'once'});assert.equal(s.events('bot').length,1);s.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('RFB filter handles fragmentation and strips input, clipboard and unsafe encodings',()=>{const f=new ReadOnlyRfbFilter();const handshake=Buffer.concat([Buffer.from('RFB 003.008\n'),Buffer.from([1,1])]);const key=Buffer.from([4,1,0,0,0,0,0,65]),pointer=Buffer.from([5,1,0,1,0,1]),cut=Buffer.from([6,0,0,0,0,0,0,3,65,66,67]),update=Buffer.from([3,0,0,0,0,0,0,10,0,10]);const output=[];for(const b of Buffer.concat([handshake,key,pointer,cut,update]))output.push(...f.push(Buffer.from([b])));assert.deepEqual(Buffer.concat(output),Buffer.concat([handshake,update]));assert.throws(()=>f.push(Buffer.from([7])),/not permitted/);});
test('only an explicit same-job followup can steer',async()=>{const f=fixture();try{const a=f.broker.submit(request('a'));f.broker.submit(request('b'));await f.broker.tick();f.broker.submit({...request('a','a-followup'),action:'followup',task:'correct this job'});await f.broker.tick();assert.equal(f.calls.length,2);assert.equal(f.calls[1].steer,'correct this job');assert.equal(f.calls[1].id,f.broker.get(a.jobKey).asideSessionId);}finally{await f.close();}});
test('queue expiry starts no native work',async()=>{const f=fixture();try{const a=f.broker.submit(request('a'));f.setNow(2_800_001);await f.broker.tick();assert.equal(f.calls.length,0);assert.equal(f.broker.get(a.jobKey).status,'expired');}finally{await f.close();}});
