import { isAbsolute, resolve } from "node:path";
import { isPathWithin, realpathNearestExisting } from "../../shared/node/paths.js";
export class SandProtectedPathError extends Error { constructor(message: string, options?: ErrorOptions) { super(message, options); this.name = "SandProtectedPathError"; } }
export function refusalMessage(path: string): string { return `Path is inside a protected host-only store and was refused: ${path}`; }
// realpath can fail with EACCES/EPERM when a path traverses a host directory this process cannot
// enter — most importantly box-virtual paths such as /root/.cursor/projects/workspace/terminals/N.txt,
// which are meaningful only after the box daemon maps them and are NOT real host paths. In that case
// the symlink-escape realpath check is impossible, so fall back to literal-path containment only
// (the path is inaccessible on the host regardless, so it cannot escape via a host symlink).
async function realpathOrUndefined(path: string): Promise<string | undefined> { try { return await realpathNearestExisting(path); } catch { return undefined; } }
export async function assertPathOutsideProtectedRoots(protectedRoots: readonly string[], candidatePath: string, baseDir: string, allowedRoots: readonly string[] = []): Promise<void> { if (protectedRoots.length === 0) return; const resolved = isAbsolute(candidatePath) ? resolve(candidatePath) : resolve(baseDir, candidatePath); const realResolved = await realpathOrUndefined(resolved); for (const allow of allowedRoots) { if (!isPathWithin(allow, resolved, { isInclusive: true })) continue; if (realResolved === undefined) return; const realAllow = await realpathOrUndefined(allow); if (realAllow === undefined || isPathWithin(realAllow, realResolved, { isInclusive: true })) return; } for (const root of protectedRoots) if (isPathWithin(root, resolved, { isInclusive: true })) throw new SandProtectedPathError(refusalMessage(candidatePath)); if (realResolved !== undefined) for (const root of protectedRoots) { const realRoot = await realpathOrUndefined(root); if (realRoot !== undefined && isPathWithin(realRoot, realResolved, { isInclusive: true })) throw new SandProtectedPathError(refusalMessage(candidatePath)); } }
